"""
Python classes generated from global namespace FlatBuffers
schema definitions.
"""

# Automatically generated by the FlatBuffers compiler, do not modify.

import flatbuffers


class Void(object):
    """
    Void type (table based) for use with services.
    """
    __slots__ = ['_tab']

    @staticmethod
    def from_buffer(buf: object, offset: int):
        """
        Create object from buffer.

        :param buf: Anything with a Buffer interfaces. See the Python
            `buffer docs <https://docs.python.org/3/c-api/buffer.html>`_.
        :param offset: The offset into the buffer to create the object from.
        """
        base = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        obj = Void(buf, base + offset)
        return obj

    def __init__(self, buf: object, pos: int):
        """

        :param buf: Anything with a Buffer interfaces. See the Python
            `buffer docs <https://docs.python.org/3/c-api/buffer.html>`_.
        :param offset: The offset into the buffer to create the object from.
        """
        self._tab = flatbuffers.table.Table(buf, pos)

    @staticmethod
    def start(builder: flatbuffers.Builder):
        """

        Start a new object in the buffer held by the builder.

        :param builder: The FlatBuffers builder object to use.
        """
        builder.StartObject(0)

    @staticmethod
    def end(builder: flatbuffers.Builder):
        """

        End an object in the buffer held by the builder.

        :param builder: The FlatBuffers builder object to use.
        """
        return builder.EndObject()
